# Generated by Django 5.1.3 on 2025-02-04 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Source d'actualité",
                'verbose_name_plural': "Sources d'actualités",
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.URLField(verbose_name="URL de l'article")),
                ('image_url', models.URLField(blank=True, null=True, verbose_name="URL de l'image")),
                ('published_at', models.DateTimeField(verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('category', models.CharField(blank=True, max_length=1000, verbose_name='Catégorie')),
                ('views_count', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newssource', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article sauvegardé',
                'verbose_name_plural': 'Articles sauvegardés',
            },
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['-published_at'], name='news_newsar_publish_db2481_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['category'], name='news_newsar_categor_ed8dc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='newsarticle',
            constraint=models.UniqueConstraint(fields=('url', 'published_at'), name='unique_article'),
        ),
        migrations.AlterUniqueTogether(
            name='savedarticle',
            unique_together={('user', 'article')},
        ),
    ]
