# Generated by Django 5.1.3 on 2025-02-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=2000, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(max_length=500, verbose_name="URL de l'article"),
        ),
    ]
