# Generated by Django 5.1.3 on 2025-03-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_title_alter_newsarticle_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedArticle',
        ),
    ]
