# Generated by Django 5.1.3 on 2025-04-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
