# Generated by Django 5.1.3 on 2025-03-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelUser', '0002_user_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
    ]
