"""
Django settings for ForumInsta project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Charger les variables d'environnement
load_dotenv()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


NEWS_API_KEY = os.getenv('NEWS_API_KEY')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY') 
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Indiquer les templates personnalisés pour les erreurs 404 et 403 
handler404 = 'home.views.custom_404' 
handler403 = 'home.views.custom_403'

# Change le titre de l'onglet du navigateur
ADMIN_SITE_HEADER = "InstaForum Administration"

# Change le titre de la page de connexion
ADMIN_SITE_TITLE = "InstaForum Admin Portal"

# Change le texte de la barre de navigation
ADMIN_INDEX_TITLE = "Bienvenue sur le portail d'administration InstaForum"


ALLOWED_HOSTS = ["*"]



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'api',
    'modelUser',
    'home',
    'forum',
    'news',
    'events',
    'newsletter',
    'messaging',
    'resources',

    "anymail",
    'taggit',
    'channels',
    'django_celery_beat',
    'django_celery_results',
    'debug_toolbar',
    'crispy_forms',
    'crispy_bootstrap4',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django_filters',
    'admin_interface',
    'colorfield',
    
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

# Configuration Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Paris'

X_FRAME_OPTIONS = 'SAMEORIGIN' # nécessaire pour le chargement de l'interface

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'fetch_and_store_news_every_5_minutes': {
        'task': 'news.tasks.fetch_and_store_news',
        'schedule': crontab(minute='*/30'),
        # 'args': (),  # Ajoutez des arguments si nécessaire
    },
}
CELERY_BEAT_SCHEDULE = {
    'fetch_and_active_suspended_user_2_min': {
        'task': 'modelUser.tasks.check_suspended_users',
        'schedule': crontab(minute='*/2'),
        # 'args': (),  # Ajoutez des arguments si nécessaire
    },
}

# Autoriser toutes les origines (à utiliser avec précaution)
CORS_ALLOW_ALL_ORIGINS = True


CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'x-csrftoken',
    'x-requested-with',
    # Ajoutez d'autres en-têtes si nécessaire
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'DELETE',
    'OPTIONS',
    'PATCH',
]

CORS_ALLOW_CREDENTIALS = True



SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
     'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'debug_toolbar.middleware.DebugToolbarMiddleware',

    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
]


ROOT_URLCONF = 'ForumInsta.urls'

ACCOUNT_ADAPTER = 'modelUser.adapter.MyAccountAdapter'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'forum.context_processors.notification_count',
            ],
        },
    },
]


DEFAULT_CHARSET = 'utf-8'

# WSGI_APPLICATION = 'ForumInsta.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE':'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST'),
        'PORT': os.getenv('DATABASE_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr'
TIME_ZONE = 'Africa/Ndjamena'
USE_I18N = True
USE_L10N = True
USE_TZ = True

from django.utils.translation import gettext_lazy as _

LANGUAGES = [ 
    ('en', _('English')), 
    ('fr', _('Français')),
    ('ar', _('العربية')),  ]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL ='modelUser.User'

ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True 
ACCOUNT_USERNAME_REQUIRED = True  
ACCOUNT_EMAIL_VERIFICATION = 'optional'
LOGIN_REDIRECT_URL ='/next'
ACCOUNT_PASSWORD_CHANGE_REDIRECT_URL = 'account_profile' 

# Durée de session par défaut
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7 * 2  # 2 semaines
CRISPY_TEMPLATE_PACK = 'bootstrap4'
# Durée de session prolongée pour "Se souvenir de moi"
ACCOUNT_SESSION_REMEMBER = True



EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"
# DEFAULT_FROM_EMAIL = "instaforum2025@gmail.com"

# ANYMAIL = {
#     "BREVO_API_KEY": os.getenv('BREVO_API_KEY'),
#     "IGNORE_UNSUPPORTED_FEATURES": True,
# }

AUTHENTICATION_BACKENDS = [
    'modelUser.authentication.EmailOrUsernameBackend',  # Ajoute ton backend personnalisé ici
    'django.contrib.auth.backends.ModelBackend',  
    'allauth.account.auth_backends.AuthenticationBackend',]

ACCOUNT_FORMS = {
    'login': 'modelUser.forms.CustomLoginForm',
    'signup': 'modelUser.forms.CustomSignupForm',
    'reset_password': 'modelUser.forms.CustomResetPasswordForm',
    'change_password': 'modelUser.forms.CustomChangePasswordForm',  # Nouveau
    'set_password': 'modelUser.forms.CustomSetPasswordForm',  # Nouveau
}


ASGI_APPLICATION = 'ForumInsta.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)], 
        },
    },
}




LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'encoding': 'utf-8', 
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'news': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'channels': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        'django.channels': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}



INTERNAL_IPS = ['127.0.0.1']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

}





from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}


JAZZMIN_SETTINGS = {
    # Titres et identité
    "site_title": "Insta pour nous",
    "site_header": "Administration",
    "site_brand": "InstaForum",
    "welcome_sign": "Bienvenue sur le portail d'administration InstaForum",
    "copyright": "abakarix4dev © 2025",
    
    # Personnalisation de l'apparence
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "custom_css": "css/custom.css",
    "user_avatar": "avatars/admin_avatar.png",
    
    # Page d'accueil personnalisée
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Voir le site", "url": "/", "new_window": True},
        {"app": "auth", "name": "Utilisateurs"},
        {"model": "auth.User"},
    ],
    
    # Organisation des modèles dans des menus
    "order_with_respect_to": ["auth", "blog", "media", "comments"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "blog.Post": "fas fa-newspaper",
        "media.Media": "fas fa-photo-video",
        "comments.Comment": "fas fa-comments",
    },
    
    # Menus personnalisés
    "menu": [
        {
            "name": "Utilisateurs",
            "icon": "fas fa-users",
            "models": [
                "auth.User",
                "auth.Group",
                "accounts.Profile",
            ]
        },
        {
            "name": "Contenu",
            "icon": "fas fa-newspaper",
            "models": [
                "blog.Post", 
                "blog.Category"
            ]
        },
        {
            "name": "Médias",
            "icon": "fas fa-photo-video",
            "models": [
                "media.Image",
                "media.Video"
            ]
        },
        {
            "name": "Interactions",
            "icon": "fas fa-comments",
            "models": [
                "comments.Comment",
                "likes.Like"
            ]
        },
        {
            "name": "Statistiques",
            "url": "admin:stats_dashboard",
            "icon": "fas fa-chart-line",
        },
    ],
    
    # Actions personnalisées
    "custom_links": {
        "blog.Post": [
            {
                "name": "Publier sur les réseaux", 
                "url": "publish_to_socials/", 
                "icon": "fas fa-share-alt"
            }
        ],
        "accounts.Profile": [
            {
                "name": "Envoyer email groupé", 
                "url": "send_bulk_email/", 
                "icon": "fas fa-envelope"
            }
        ],
    },
    
    # Personnalisation du tableau de bord
    "dashboard_widgets": [
        {
            "type": "recent_actions",
            "limit": 10,
            "title": "Actions récentes"
        },
        {
            "type": "model_list",
            "title": "Création rapide",
            "models": ["blog.Post", "media.Image", "comments.Comment"]
        },
        {
            "type": "chart",
            "title": "Activité du site",
            "url": "admin:site_activity_chart"
        },
        {
            "type": "html",
            "title": "Infos & Documentation",
            "content": """
            <p>Bienvenue sur le panneau d'administration InstaForum.</p>
            <ul>
                <li><a href="/docs/admin/" target="_blank">Documentation</a></li>
                <li><a href="https://github.com/abakarix4dev/instaforum" target="_blank">Code source</a></li>
            </ul>
            """
        },
    ],
    
    # Navigation latérale et supérieure
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": ["auth.Group"],
    "related_modal_active": True,
    
    # Boutons d'actions supplémentaires
    "actions_sticky_top": True,
    "custom_buttons": [
        {
            "name": "Exporter en CSV",
            "action": "export_as_csv",
            "classes": "btn btn-success",
            "icon": "fas fa-file-csv",
        }
    ],
}

# Configuration supplémentaire pour la personnalisation UI
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}