# Generated by Django 5.1.3 on 2025-03-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userblock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='userblock',
            name='blocker',
        ),
        migrations.DeleteModel(
            name='SharedLink',
        ),
        migrations.DeleteModel(
            name='UserBlock',
        ),
    ]
